################################################################################
# \file program.mk
#
# \brief
# This make file is called recursively and is used to build the
# resoures file system. It is expected to be run from the example directory.
#
################################################################################
# \copyright
# Copyright 2018-2021 Cypress Semiconductor Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

include $(MTB_TOOLS__RECIPE_DIR)/make/recipe/program_common.mk

_MTB_RECIPE__GDB_ARGS=$(MTB_TOOLS__RECIPE_DIR)/make/scripts/gdbinit
_MTB_RECIPE__OPENOCD_DEBUG_PREFIX=$(_MTB_RECIPE_OPENOCD_CHIP_NAME).cm33 configure -rtos auto -rtos-wipe-on-reset-halt 1; gdb_breakpoint_override hard;

ifeq ($(TOOLCHAIN),A_Clang)
_MTB_RECIPE__OPENOCD_PROGRAM_IMG=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).bin $(TOOLCHAIN_VECT_BASE_CM33)
else
_MTB_RECIPE__OPENOCD_SYMBOL_IMG=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).$(MTB_RECIPE__SUFFIX_TARGET)
ifeq ($(APPTYPE),ram)
_MTB_RECIPE__OPENOCD_PROGRAM_IMG=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).bin
else
# TODO update this to use hex file once generated by postbuild
_MTB_RECIPE__OPENOCD_PROGRAM_IMG=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).final.bin 0x60000000
endif
endif

# Multi-core application programming: always use combined HEX image
ifneq ($(_MTB_RECIPE__APP_HEX_FILE),)
_MTB_RECIPE__OPENOCD_PROGRAM_IMG=$(_MTB_RECIPE__APP_HEX_FILE)
endif

# Use custom HEX image when PROG_FILE was provided by the user
ifneq ($(PROG_FILE),)
_MTB_RECIPE__OPENOCD_PROGRAM_IMG=$(PROG_FILE)
endif

ifeq ($(APPTYPE),ram)
ifeq ($(filter erase,$(MAKECMDGOALS)),erase)
$(call mtb__error, Unable to proceed. program and erase is not supported for APPTYPE=$(APPTYPE)))
endif
_MTB_RECIPE_APP_LOAD_ADDR=0x20004200
_MTB_RECIPE_APP_SP=$(_MTB_RECIPE_APP_LOAD_ADDR)
_MTB_RECIPE_APP_PC=$(shell printf "0x%x" $$(($(_MTB_RECIPE_APP_LOAD_ADDR) + 0x04)))
_MTB_RECIPE_OPENOCD_PREPARE_APP=init; reset init; load_image $(_MTB_RECIPE__OPENOCD_PROGRAM_IMG) $(_MTB_RECIPE_APP_LOAD_ADDR); reg sp [mrw $(_MTB_RECIPE_APP_SP)]; reg pc [mrw $(_MTB_RECIPE_APP_PC)];
_MTB_RECIPE_OPENOCD_DEBUG=$(_MTB_RECIPE__OPENOCD_DEBUG_PREFIX) $(_MTB_RECIPE_OPENOCD_PREPARE_APP)
_MTB_RECIPE_OPENOCD_PROGRAM=$(_MTB_RECIPE_OPENOCD_PREPARE_APP) resume; exit;

else
_MTB_RECIPE_OPENOCD_ERASE=init; reset init; erase_all; exit;
_MTB_RECIPE_OPENOCD_DEBUG=$(_MTB_RECIPE__OPENOCD_DEBUG_PREFIX) init; reset init;
_MTB_RECIPE_OPENOCD_PROGRAM=program $(_MTB_RECIPE__OPENOCD_PROGRAM_IMG) verify reset exit;
endif

_MTB_RECIPE__OPENOCD_ERASE_ARGS=$(_MTB_RECIPE__OPENOCD_SCRIPTS) $(_MTB_RECIPE__OPENOCD_QSPI) -c \
					"$(_MTB_RECIPE__OPENOCD_QSPI_FLASHLOADER); $(_MTB_RECIPE__OPENOCD_INTERFACE) $(_MTB_RECIPE__OPENOCD_TARGET) $(_MTB_RECIPE_OPENOCD_CUSTOM_COMMAND) $(_MTB_RECIPE_OPENOCD_ERASE)"
_MTB_RECIPE__OPENOCD_PROGRAM_ARGS=$(_MTB_RECIPE__OPENOCD_SCRIPTS) $(_MTB_RECIPE__OPENOCD_QSPI) -c \
					"$(_MTB_RECIPE__OPENOCD_QSPI_FLASHLOADER); $(_MTB_RECIPE__OPENOCD_INTERFACE) $(_MTB_RECIPE__OPENOCD_TARGET) $(_MTB_RECIPE_OPENOCD_CUSTOM_COMMAND) $(_MTB_RECIPE_OPENOCD_PROGRAM)"
_MTB_RECIPE__OPENOCD_DEBUG_ARGS=$(_MTB_RECIPE__OPENOCD_SCRIPTS) $(_MTB_RECIPE__OPENOCD_QSPI) -c \
					"$(_MTB_RECIPE__OPENOCD_QSPI_FLASHLOADER); $(_MTB_RECIPE__OPENOCD_INTERFACE) $(_MTB_RECIPE__OPENOCD_TARGET) $(_MTB_RECIPE_OPENOCD_CUSTOM_COMMAND) $(_MTB_RECIPE_OPENOCD_DEBUG)"
