################################################################################
# \file program.mk
#
# \brief
# This make file is called recursively and is used to build the
# resoures file system. It is expected to be run from the example directory.
#
################################################################################
# \copyright
# Copyright 2018-2021 Cypress Semiconductor Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

include $(CY_INTERNAL_BASELIB_PATH)/make/recipe/program_common.mk

CY_GDB_ARGS=$(CY_INTERNAL_BASELIB_PATH)/make/scripts/gdbinit
CY_OPENOCD_DEBUG_PREFIX=$(CY_OPENOCD_CHIP_NAME).cm33 configure -rtos auto -rtos-wipe-on-reset-halt 1; gdb_breakpoint_override hard;

ifeq ($(TOOLCHAIN),A_Clang)
CY_OPENOCD_PROGRAM_IMG=$(CY_CONFIG_DIR)/$(APPNAME).bin $(TOOLCHAIN_VECT_BASE_CM33)
else
CY_OPENOCD_SYMBOL_IMG=$(CY_CONFIG_DIR)/$(APPNAME).$(CY_TOOLCHAIN_SUFFIX_TARGET)
ifeq ($(APPTYPE),ram)
CY_OPENOCD_PROGRAM_IMG=$(CY_CONFIG_DIR)/$(APPNAME).bin
else
# TODO update this to use hex file once generated by postbuild
CY_OPENOCD_PROGRAM_IMG=$(CY_CONFIG_DIR)/$(APPNAME).final.bin 0x60000000
endif
endif

ifeq ($(APPTYPE),ram)
ifeq ($(filter erase,$(MAKECMDGOALS)),erase)
$(call CY_MACRO_ERROR, Unable to proceed. program and erase is not supported for APPTYPE=$(APPTYPE)))
endif
CY_APP_LOAD_ADDR=0x20004200
CY_APP_SP=$(CY_APP_LOAD_ADDR)
CY_APP_PC=$(shell printf "0x%x" $$(($(CY_APP_LOAD_ADDR) + 0x04)))
CY_OPENOCD_PREPARE_APP=init; reset init; load_image $(CY_OPENOCD_PROGRAM_IMG) $(CY_APP_LOAD_ADDR); reg sp [mrw $(CY_APP_SP)]; reg pc [mrw $(CY_APP_PC)];
CY_OPENOCD_DEBUG=$(CY_OPENOCD_DEBUG_PREFIX) $(CY_OPENOCD_PREPARE_APP)
CY_OPENOCD_PROGRAM=$(CY_OPENOCD_PREPARE_APP) resume; exit;

else
CY_OPENOCD_ERASE=init; reset init; erase_all; exit;
CY_OPENOCD_DEBUG=$(CY_OPENOCD_DEBUG_PREFIX) init; reset init;
CY_OPENOCD_PROGRAM=program $(CY_OPENOCD_PROGRAM_IMG) verify reset exit;
endif

CY_OPENOCD_ERASE_ARGS=$(CY_OPENOCD_SCRIPTS) $(CY_OPENOCD_QSPI) -c \
					"$(CY_OPENOCD_QSPI_FLASHLOADER); $(CY_OPENOCD_INTERFACE) $(CY_OPENOCD_TARGET) $(CY_OPENOCD_CUSTOM_COMMAND) $(CY_OPENOCD_ERASE)"
CY_OPENOCD_PROGRAM_ARGS=$(CY_OPENOCD_SCRIPTS) $(CY_OPENOCD_QSPI) -c \
					"$(CY_OPENOCD_QSPI_FLASHLOADER); $(CY_OPENOCD_INTERFACE) $(CY_OPENOCD_TARGET) $(CY_OPENOCD_CUSTOM_COMMAND) $(CY_OPENOCD_PROGRAM)"
CY_OPENOCD_DEBUG_ARGS=$(CY_OPENOCD_SCRIPTS) $(CY_OPENOCD_QSPI) -c \
					"$(CY_OPENOCD_QSPI_FLASHLOADER); $(CY_OPENOCD_INTERFACE) $(CY_OPENOCD_TARGET) $(CY_OPENOCD_CUSTOM_COMMAND) $(CY_OPENOCD_DEBUG)"
